---
title: "Accommodation"
---

#### Affordable housing

**Albergue Seminario Menor**

[Website](https://www.alberguesdelcamino.com/santiago/albergue-seminario-menor/)
Address: Av. de Quiroga Palacios, 2A, 15702 Santiago de Compostela, A Coruña, Spain 
Telephone: +34 881 03 17 68
[santiago@alberguesdelcamino.com](mailto:santiago@alberguesdelcamino.com)


#### Recommended hotels in Santiago de Compostela

**Costa Vella**  
[Website](https://www.costavella.com/)  
Address: C/ Porta da Pena, 17, 15704, Santiago de Compostela, A Coruña, Spain  
Telephone: +34 981 56 95 30  
[hotelcostavella@costavella.com](mailto:hotelcostavella@costavella.com)


**Hotel Convento de San Francisco**  
[Website](https://www.sanfranciscohm.com/es/)  
Address: Campillo de San Francisco, 3, 15705, Santiago de Compostela, A Coruña, Spain  
Telephone: +34 981 58 16 34  
[hotel@sanfranciscohm.com](mailto:hotel@sanfranciscohm.com)

**Hospedería San Martiño Pinario**  
[Website](https://www.sanmartinpinario.es/es/index.html)  
Address: Praza Inmaculada 3, 15704, Santiago de Compostela, A Coruña, Spain  
Telephone: +34 981 56 02 82  
[reservas@sanmartinpinario.eu](mailto:reservas@sanmartinpinario.eu)

**Hotel Pazo de Altamira**  
[Website](https://www.pazodealtamira.com/)  
Address: Rúa de Altamira, 18, 15704, Santiago de Compostela, A Coruña, Spain  
Telephone:  + 34 981 55 85 42  
[reservas@pazodealtamira.com](mailto:reservas@pazodealtamira.com)

**Eurostars**  
[Website](https://www.eurostarshotels.com/hoteles-en-espana-santiago-de-compostela.html?referer_code=bs0gg20ww&gclid=EAIaIQobChMIu-3BtK2RggMV_z0GAB1OzAQ4EAAYASAAEgIv6PD_BwE)  
Address:  
- Hotel Eurostars Araguaney, 5\*, Alfredo Brañas 5  
- Eurostars Gran Hotel Santiago, 4\*, Avenida Maestro Mateo 27  
- Eurostars San Lázaro, 4\*, Avenida Fernando de Casas Novoa s/n  
- Hotel Exe Area Central, 3\*, Rua París, 7 C.C. Área Central  
- Exe Peregrino, 4\*, Avda. Rosalía de Castro, s/n  
Telephone: +34 913 34 21 96


**Albergue Seminario Menor**  
[Website](https://www.alberguesdelcamino.com/santiago/albergue-seminario-menor/)  
Address: Avda. Quiroga Palacios s/n, 15703, Santiago De Compostela, A Coruña, Spain  
Telephone: +34 881 031 768  
[santiago@alberguesdelcamino.com](mailto:santiago@alberguesdelcamino.com)
