---
title: "Registration"
---

To register for the congress, please access [**this registration form**](https://docs.google.com/forms/d/e/1FAIpQLSezvTsL-kR1efQFeVp0Bk3UNlLhD5CL07A5UGiEeI3wkVC-OA/viewform).
```{=html}
<style>
  .cubicolo {
    border: #0000ff;
    /* display: flex; */
    align-items: center;
    background-color: #dde9f3;
    border-radius: 5px;
    padding: 12px;
    font-size: 24px;
  }
  .muoviti {
    border: #0000ff;
    align-items: center;
    /* background-color: #dde9f3; */
    border-radius: 5px;
    padding: 9px;
    font-size: 18px;
  }
</style>

<strong class='cubicolo'>Registration Fee: 160€</strong>
<br>
<br>
<strong>Deadline: 23:59:59 - 23rd April 2024</strong>
```
## Payment Instructions
### Credit Card
You can access the credit card payment from [this link](https://matricula.usc.es/autoliquidacions/Frm_Economica_Autoliquidaciones.asp?lang=10)

- Where it says **DNI (ID)** please choose "passport" from the tab
- Where it says **Concept**, please choose "Congress --> XII IBERIAN PRION CONFERENCE" from the tab.
- Amount, 160

Then you click on "I am not a robot" and "next".
This will take you to the payment finalization section which unfortunately is not in English. In the first page you need to check the box to agree with terms and conditions ("Acepto os termos e condicións"), then click on "iniciar pagamento", and then enter your credit card number "tarxeta", its date of expiration "data de caducidade" and pin "codigo de seguridade". And submit...
The system accepts MasterCard and Visa.

### Bank Transfer
<strong>Important: please indicate "Iberian Prion Conference & *YOUR NAME*"</strong>
<p>Banco Santander Central Hispano<br>
Address: Rúa Caldeirería 54-56, 15703 Santiago de Compostela<br>
Account holder: University of Santiago de Compostela<br>
Account number: 0049 2584 90 2214002210<br>
IBAN: ES40 0049 2584 9022 1400 2210<br>
SWIFT: BSCHESMM</p>

```{=html}
<style>
  .carosello-prionico{
    gap: 10px;
  }

  .carosello-prionico img {
    height: 300px;
  }
</style>

<div id="randomizzazione-prionica" class="carosello-prionico"></div>

<script>
  //Add images to poster.qmd with style='display: none;' so quarto will load them
  var images = [
    "figures/fig4.jpg",
    "figures/fig5.jpg",
    "figures/prion_fig2.jpg",
    "figures/prion_fig1.jpg",
    "figures/prion_fig3.jpg"
  ];
  var randomImage = images[Math.floor(Math.random() * images.length)];
  var imgElement = document.createElement('img');
  imgElement.src = randomImage;
  document.getElementById('randomizzazione-prionica').appendChild(imgElement);
</script>
```